/**
 * Parses the seed CSVs in data/ and emits typed TypeScript data files into src/data/.
 * Run via: npm run build:data
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

function readCsv(name: string): Record<string, string>[] {
  const text = readFileSync(resolve(root, 'data', name), 'utf-8');
  const lines = text.trim().split('\n').map(l => l.trim());
  const headers = lines[0].split(',');
  return lines.slice(1).map(line => {
    const vals = line.split(',');
    const row: Record<string, string> = {};
    headers.forEach((h, i) => { row[h.trim()] = (vals[i] ?? '').trim(); });
    return row;
  });
}

function num(s: string): number | null {
  const n = parseFloat(s);
  return isNaN(n) ? null : n;
}

// ─── Feather Stats ───────────────────────────────────────────────────────────

const statColumns: [string, string][] = [
  ['PvP DMG Bonus',    'PvPDmgBonus'],
  ['PvP DMG Reduction','PvPDmgReduction'],
  ['Ignore PDEF',      'IgnorePDEF'],
  ['Ignore MDEF',      'IgnoreMDEF'],
  ['PDMG',             'PDMG'],
  ['MDMG',             'MDMG'],
  ['PATK',             'PATK'],
  ['MATK',             'MATK'],
  ['PvE DMG Bonus',    'PvEDmgBonus'],
  ['PvE DMG Reduction','PvEDmgReduction'],
  ['PDEF',             'PDEF'],
  ['MDEF',             'MDEF'],
  ['HP',               'HP'],
  ['PDMG Reduction',   'PDMGReduction'],
  ['MDMG Reduction',   'MDMGReduction'],
  ['INT/DEX/STR',      'INTDEXSTR'],
  ['VIT',              'VIT'],
];

const featherRows = readCsv('feather-stats.csv');

// Group by feather name, collect tiers
const featherMap = new Map<string, {
  type: string; set: string; rarity: string;
  tiers: { tier: number; costToNext: number | null; totalCost: number; stats: Record<string, number> }[];
}>();

for (const row of featherRows) {
  const id = row['Feather'];
  const tier = parseInt(row['Tier']);
  if (!featherMap.has(id)) {
    featherMap.set(id, { type: row['Type'], set: row['Set'], rarity: row['Rarity'], tiers: [] });
  }
  const stats: Record<string, number> = {};
  for (const [csvCol, key] of statColumns) {
    const v = num(row[csvCol]);
    if (v !== null && v !== 0) stats[key] = v;
  }
  featherMap.get(id)!.tiers.push({
    tier,
    costToNext: num(row['Cost to Next Tier']),
    totalCost: num(row['Total Cost']) ?? 0,
    stats,
  });
}

const feathersTs = `// AUTO-GENERATED by scripts/build-data.ts — do not edit by hand
import type { FeatherDef } from '../domain/types';

export const feathers: FeatherDef[] = ${JSON.stringify(
  Array.from(featherMap.entries()).map(([id, def]) => ({
    id,
    type: def.type,
    set: def.set,
    rarity: def.rarity,
    tiers: def.tiers.sort((a, b) => a.tier - b.tier),
  })),
  null, 2
)};

export const featherById = new Map<string, FeatherDef>(feathers.map(f => [f.id, f]));
`;

// ─── Set Bonuses ─────────────────────────────────────────────────────────────

function parseSetBonuses(filename: string, isAttack: boolean) {
  const rows = readCsv(filename);
  return rows.map(row => {
    const tier = parseInt(row['Tier']);
    const flat: Record<string, number> = {};
    const pct: Record<string, number> = {};
    if (isAttack) {
      const patk = num(row['PATK']); if (patk) flat['PATK'] = patk;
      const matk = num(row['MATK']); if (matk) flat['MATK'] = matk;
      const pvpDmg = num(row['PvP DMG Bonus']); if (pvpDmg) flat['PvPDmgBonus'] = pvpDmg;
      const pctAtk = num(row['Attack Stats Percentage Bonus']); if (pctAtk) pct['attack'] = pctAtk;
      const pctPvE = num(row['PvE Stats Percentage Bonus']); if (pctPvE) pct['pve'] = pctPvE;
      const pctPvP = num(row['PvP Stats Percentage Bonus']); if (pctPvP) pct['pvp'] = pctPvP;
    } else {
      const hp = num(row['HP']); if (hp) flat['HP'] = hp;
      const pvpRed = num(row['PvP DMG Reduction']); if (pvpRed) flat['PvPDmgReduction'] = pvpRed;
      const pctDef = num(row['Defense Stats Percentage Bonus']); if (pctDef) pct['defense'] = pctDef;
      const pctPvE = num(row['PvE Stats Percentage Bonus']); if (pctPvE) pct['pve'] = pctPvE;
      const pctPvP = num(row['PvP Stats Percentage Bonus']); if (pctPvP) pct['pvp'] = pctPvP;
    }
    return { tier, flat, pct };
  });
}

const attackBonuses = parseSetBonuses('attack-set-bonuses.csv', true);
const defenseBonuses = parseSetBonuses('defense-set-bonuses.csv', false);

const setBonusesTs = `// AUTO-GENERATED by scripts/build-data.ts — do not edit by hand
import type { SetBonus } from '../domain/types';

export const attackSetBonuses: SetBonus[] = ${JSON.stringify(attackBonuses, null, 2)};

export const defenseSetBonuses: SetBonus[] = ${JSON.stringify(defenseBonuses, null, 2)};

export function getAttackBonus(minTier: number): SetBonus {
  return attackSetBonuses[minTier - 1] ?? attackSetBonuses[0];
}

export function getDefenseBonus(minTier: number): SetBonus {
  return defenseSetBonuses[minTier - 1] ?? defenseSetBonuses[0];
}
`;

// ─── Write files ─────────────────────────────────────────────────────────────

writeFileSync(resolve(root, 'src/data/feathers.generated.ts'), feathersTs);
writeFileSync(resolve(root, 'src/data/setBonuses.generated.ts'), setBonusesTs);

console.log('✓ src/data/feathers.generated.ts');
console.log('✓ src/data/setBonuses.generated.ts');
